server:
  port: 9090


spring:
    datasource:
        name: mysql_dev
        type: com.alibaba.druid.pool.DruidDataSource
        #druid相关配置
        druid:
          #监控统计拦截的filters
          filters: stat
          driver-class-name: com.mysql.jdbc.Driver
          #基本属性
          url: jdbc:mysql://112.125.25.43:3389/chicken_pro?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
          username: root
          password: xiaoji!@#qwe
          #配置初始化大小/最小/最大
          initial-size: 1
          min-idle: 1
          max-active: 20
          #获取连接等待超时时间
          max-wait: 60000
          #间隔多久进行一次检测，检测需要关闭的空闲连接
          time-between-eviction-runs-millis: 60000
          #一个连接在池中最小生存的时间
          min-evictable-idle-time-millis: 300000
          validation-query: SELECT 'x'
          test-while-idle: true
          test-on-borrow: false
          test-on-return: false
          #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
          pool-prepared-statements: false
          max-pool-prepared-statement-per-connection-size: 20
    redis:
      database: 0
      host: 127.0.0.1
      port: 1234
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 500
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 10000
        # 连接池中的最小空闲连接
        min-idle: 0
      timeout: 200
      #从连接池获取连接时是否检验链接有效性
      testOnBorrow: true
      expiration: 600
      password: '11111'
    freemarker:
      cache: false
      template-loader-path: classpath:/freemarker/
      charset: UTF-8
      check-template-location: true
      content-type: text/html
      expose-request-attributes: true
      expose-session-attributes: true
      request-context-attribute: request
      suffix: .ftl

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.chickenken.model
  configuration:
    call-setters-on-nulls: true



#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
    returnPageInfo: check
